#!/bin/sh

package_dir=$1
server=$2
remote_dir=$3

if [ "${package_dir}" = "" ] || [ "${server}" = "" ] || [ "${remote_dir}" = "" ]
then
	echo "Usage:  $0 <package directory> <server> <directory>"
	echo "  e.g., $0 ../../ports/packages servername /var/www/packages"
	exit 1
fi

if ! [ -d "${package_dir}" ]
then
	echo "${package_dir} is not a directory!"
	exit 1
fi

if ! [ -d "${package_dir}/All" ]
then
	echo "${package_dir} contains no 'All' directory!"
	exit 1
fi

# Assume that the build and target architecture are the same:
architecture=`sysctl -n hw.machine_arch`

# Get the build jail version:
major_version=`cat ${package_dir}/.jailversion | awk -F. '{ print $1 }'`

abi_dir="${remote_dir}/FreeBSD:${major_version}:${architecture}"
date=`stat -f '%Sm' -t '%Y-%m-%d-%H%M' ${package_dir}/All`
path="${abi_dir}/${date}"

echo "Creating ${server}:${path} ..."
ssh ${server} "mkdir -p ${path}" || exit 1

echo "Synchronizing from ${package_dir} to ${server} ..."
to_sync=`find ${package_dir} -mindepth 1 -maxdepth 1 -not -name '.building'`
rsync -avz -e ssh ${to_sync} ${server}:${path}/ || exit 1

echo "Symlinking 'latest' to ${date} ..."
ssh ${server} "rm -f ${abi_dir}/latest" || true
ssh ${server} "ln -sf ${date} ${abi_dir}/latest" || exit 1

echo "Packages sync'ed to ${server}:${abi_dir}/latest"
