#!/bin/sh

if [ "${PORTSDIR}" = "" ]
then
	echo "PORTSDIR must be set"
	exit 1
fi

tmpfile=`mktemp -t portdeps`

echo "Finding dependencies of $*"

for port in $*
do
	echo ""
	echo "${port} depends on:"
	make -C ${PORTSDIR}/${port} all-depends-list \
		| sed "s#${PORTSDIR}/##" \
		| tee -a ${tmpfile} \
		|| exit 1
done

depsfile=`mktemp -t port-dependencies`
cat ${tmpfile} | sort | uniq > ${depsfile}

echo "`wc -l ${depsfile}` unique dependencies:"
cat ${depsfile}

rm -f ${depsfile}
rm -f ${tmpfile}
