#!/bin/sh

if [ "${PORTSDIR}" = "" ]
then
	>&2 echo "PORTSDIR must be set"
	exit 1
fi

tmpfile=`mktemp -t portdeps`

(>&2 echo "Finding dependencies of $*")

for port in $*
do
	>&2 echo ""
	>&2 echo "${port} depends on:"
	make -C ${PORTSDIR}/${port} all-depends-list \
		| sed "s#${PORTSDIR}/##" \
		| (>&2 tee -a ${tmpfile}) \
		|| exit 1
done

depsfile=`mktemp -t port-dependencies`
cat ${tmpfile} \
	| sort \
	| uniq \
	| tee -a ${depsfile} \
	| (>&2 echo "`wc -l` unique dependencies")

cat ${depsfile}

rm -f ${depsfile}
rm -f ${tmpfile}
